"use client";

import { m } from "framer-motion";
import { Card, CardContent } from "@/components/ui/Card";
import { ShieldAlert, Info, AlertTriangle, ExternalLink, Cpu, Scale, Phone } from "lucide-react";

export default function DisclaimerPage() {
  const lastUpdated = new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' });

  return (
    <div className="min-h-screen pt-24 pb-16 px-6 lg:px-8 max-w-4xl mx-auto">
      <m.div 
        initial={{ opacity: 0, y: 20 }} 
        animate={{ opacity: 1, y: 0 }}
        className="text-center mb-12"
      >
        <h1 className="text-4xl font-black font-display mb-4">Official <span className="gradient-text">Disclaimer</span></h1>
        <p className="text-muted-foreground font-medium uppercase tracking-widest text-xs">
          Last Updated: {lastUpdated}
        </p>
      </m.div>

      <Card className="premium-card border-none glass overflow-hidden">
        <CardContent className="p-8 md:p-12 space-y-12 text-foreground/80 leading-relaxed">
          
          <section className="bg-red-50/50 dark:bg-red-950/10 p-6 rounded-2xl border border-red-100 dark:border-red-900/30">
            <div className="flex items-center gap-3 mb-4 text-red-600">
              <ShieldAlert className="w-6 h-6" />
              <h2 className="text-2xl font-bold font-display text-foreground">Not an Official Government Platform</h2>
            </div>
            <p className="font-medium text-foreground">
              VoteSmart AI is an independent civic technology project. It is <span className="underline decoration-red-500 underline-offset-4">NOT</span> an official website of the Election Commission of India (ECI), the Government of India, or any State Government. We have no affiliation with any political party, candidate, or government authority.
            </p>
          </section>

          <section>
            <div className="flex items-center gap-3 mb-6 text-brand-600">
              <Info className="w-6 h-6" />
              <h2 className="text-2xl font-bold font-display text-foreground">For Official Electoral Information</h2>
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <a href="https://www.eci.gov.in" target="_blank" rel="noopener noreferrer" className="p-4 rounded-xl border border-border hover:border-brand-500 hover:bg-brand-50 dark:hover:bg-brand-900/10 transition-all group">
                <div className="flex items-center gap-3 mb-2">
                  <ExternalLink className="w-4 h-4 text-brand-600" />
                  <span className="font-bold text-foreground">ECI Official Site</span>
                </div>
                <p className="text-xs text-muted-foreground">www.eci.gov.in</p>
              </a>
              <a href="https://www.nvsp.in" target="_blank" rel="noopener noreferrer" className="p-4 rounded-xl border border-border hover:border-brand-500 hover:bg-brand-50 dark:hover:bg-brand-900/10 transition-all group">
                <div className="flex items-center gap-3 mb-2">
                  <ExternalLink className="w-4 h-4 text-brand-600" />
                  <span className="font-bold text-foreground">NVSP Portal</span>
                </div>
                <p className="text-xs text-muted-foreground">www.nvsp.in</p>
              </a>
              <div className="p-4 rounded-xl border border-border col-span-full flex items-center justify-between">
                <div className="flex items-center gap-3">
                  <Phone className="w-4 h-4 text-brand-600" />
                  <span className="font-bold text-foreground">Voter Helpline</span>
                </div>
                <span className="text-xl font-black text-brand-600">1950</span>
              </div>
            </div>
          </section>

          <section>
            <div className="flex items-center gap-3 mb-4 text-brand-600">
              <Cpu className="w-6 h-6" />
              <h2 className="text-2xl font-bold font-display text-foreground">AI-Generated Content Disclaimer</h2>
            </div>
            <p>
              Responses generated by our AI assistant are produced automatically using large language model technology. While we strive for accuracy, AI responses may contain errors, outdated information, or incomplete guidance. <span className="font-bold text-foreground">Do not make critical voting decisions based solely on AI-generated content.</span>
            </p>
          </section>

          <section>
            <div className="flex items-center gap-3 mb-4 text-brand-600">
              <Scale className="w-6 h-6" />
              <h2 className="text-2xl font-bold font-display text-foreground">No Legal or Electoral Advice</h2>
            </div>
            <p>
              Nothing on this platform constitutes legal advice or official electoral guidance. For legal issues related to voting rights, please consult a qualified legal professional or your State Election Officer.
            </p>
          </section>

          <section>
            <div className="flex items-center gap-3 mb-4 text-brand-600">
              <AlertTriangle className="w-6 h-6" />
              <h2 className="text-2xl font-bold font-display text-foreground">Accuracy of Information</h2>
            </div>
            <p>
              We make every effort to keep information up to date with current Election Commission guidelines. However, electoral rules, dates, and procedures change frequently. Always verify time-sensitive information directly with the ECI.
            </p>
          </section>

        </CardContent>
      </Card>
    </div>
  );
}

